
include $(RULES_DIR)/.config

KV_SOURCES   		= ./kv.c        \
					./kv_adapt.c    \
					./kv_api.c      \
					./kv_cli.c      \
					./kv_secure.c

MODULE_SOURCES += $(KV_SOURCES)

include $(RULES_DIR)/make_objects.mk

